name: venv
channels:
  - conda-forge
  - pytorch

dependencies:
  - python>=3.6
  - pytorch>=1.5.0
  - torchvision>=0.6.0
  - opencv>=4.2.0
  - matplotlib>=3.2.1
  - pip:
    - kornia>=0.2.1
    - pytorch-lightning>=0.7.3
